language: ruby
rvm:
- 2.2.2
script:
- bundle install
- bundle exec rake db:create db:schema:load
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: 0gVi8l2SvKjTDQlGxT97SAngjp0MXkDwpvnVLMi1UJ1mA7ZJN6Y2ReOywYvMPZcks0XirHVkIv+6vmmqB2JzavW9j7pg0Sl+wF3ZG29bgrNIRr6a0KSN5lBfZg5/oAdiy5EXgPmeUJh7n9ctE0c2AzF3WfhnVVVOhOfJAtkziwreQFi4Ro4MI9LirczT4J2arGdfO+ObunUJSU74Ziwb6yO2l243fkM90zyhZnLC8LxzvYTjsM1f+B46RYMshMKdsrEjPy1D0Pkg8n7E1BiX8Qbu7b8fwVwG0bQY/Hid0zPQaPzDsRg/7YTJ75NmY1D2fHz74zbfmOaBTj5BYa+HVTNNuz5n7VBLv42t+pVgeSf9UhXVVvvobS4gfAQe4UXL6jG0U6+yg/Fum3OsfginJMbfLZjxMt/yfIi68orpM8pfpkyUbxiLe8IJLJb54EO0arto63ZCklKmCwq0bbkz6IzmTwiOroGyM4l7N+LnHJtymk/qQhvVB3cxfxPx440xtlHt+DzkiUINHLAXgams2W6poXJk/zqFF+khRrStUFNab0lqCQXhQzi5Y0htvX5aRdCt8/relvX0CUUsncc7FaZjmys/SoZnrBTveDorVy6wtR/TwSB1ZAFZMIhoJS52dmCbxLx7sK+qdT5I/zc2gw2dyENzS2smjGzeb1Mvh7c=
  app: earmarked
  on:
    repo: TeamConchord/earmarked
    branch: master
