production:
  stripe_api_key: sk_test_Rm26JZTaimisvqCz6VgcrTxH
  stripe_publishable_key: pk_test_h555RgcdhS9pcrWigzaAj2X8

test:
  PUBLISHABLE_KEY: pk_test_h555RgcdhS9pcrWigzaAj2X8
  SECRET_KEY: sk_test_Rm26JZTaimisvqCz6VgcrTxH

development:
  twilio_sid: "AC486b47e3554bd4a1701e2504bcbba534"
  twilio_token: "44086e06872417339c2c640925cc31a2"

production:
  twilio_sid: "AC486b47e3554bd4a1701e2504bcbba534"
  twilio_token: "44086e06872417339c2c640925cc31a2"
